name: Build and Publish image

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tags
        id: tag_version
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          MAJOR_VERSION=$(echo $RELEASE_VERSION | cut -d '.' -f 1)
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tag_with_ref: false
          tag_with_sha: false
          tags: |
            ghcr.io/chrisllontop/gh-release-manager:${{ env.RELEASE_VERSION }}
            ghcr.io/chrisllontop/gh-release-manager:${{ env.MAJOR_VERSION }}

      - name: Output image tags
        run: |
          echo "Docker images with tags ${RELEASE_VERSION} and ${MAJOR_VERSION} have been pushed to GitHub Packages."
